std::string ShaderPhongTexture::vertexShaderText =
"\n"
"ATTRIBUTE vec3 VertexPosition;\n"
"ATTRIBUTE vec3 VertexNormal;\n"
"ATTRIBUTE vec2 VertexTexCoord;\n"
"\n"
"\n"
"uniform mat4 ModelViewProjectionMatrix;\n"
"uniform mat4 ModelViewMatrix;\n"
"uniform mat4 NormalMatrix;\n"
"uniform vec3 lightPosition;\n"
"\n"
"VARYING_VERT vec3 EyeVector, Normal, LightDir;\n"
"VARYING_VERT vec2 texCoord;\n"
"\n"
"#ifdef WITH_EYEPOSITION\n"
"uniform vec3 eyePosition;\n"
"#endif\n"
"\n"
"INVARIANT_POS;\n"
"void main ()\n"
"{\n"
"	Normal = vec3 (NormalMatrix * vec4 (VertexNormal, 0.0));\n"
" 	vec3 Position = vec3 (ModelViewMatrix * vec4 (VertexPosition, 1.0));\n"
"	LightDir = lightPosition - Position;\n"
"	#ifdef WITH_EYEPOSITION\n"
"		EyeVector = eyePosition-Position;\n"
"	#else\n"
"		EyeVector = -Position;\n"
"	#endif\n"
"	texCoord = VertexTexCoord;\n"
"	gl_Position = ModelViewProjectionMatrix * vec4 (VertexPosition, 1.0);\n"
"}\n";

