std::string ShaderMatCustom::vertexShaderText =
"\n"
"ATTRIBUTE vec3 VertexPosition, VertexNormal;\n"
"#ifdef WITH_COLOR\n"
"ATTRIBUTE vec3 VertexColor;\n"
"#endif\n"
"uniform mat4 TransformationMatrix;\n"
"uniform mat4 ModelViewProjectionMatrix;\n"
"uniform mat4 ModelViewMatrix;\n"
"uniform mat4 NormalMatrix;\n"
"uniform vec3 lightPosition;\n"
"VARYING_VERT vec3 EyeVector, Normal, LightDir;\n"
"\n"
"#ifdef WITH_COLOR\n"
"VARYING_VERT vec3 Color;\n"
"#endif\n"
"\n"
"#ifdef WITH_EYEPOSITION\n"
"uniform vec3 eyePosition;\n"
"#endif\n"
"\n"
"INVARIANT_POS;\n"
"void main ()\n"
"{\n"
"	Normal = vec3 (NormalMatrix * TransformationMatrix * vec4 (VertexNormal, 0.0));\n"
" 	vec3 Position = vec3 (ModelViewMatrix * TransformationMatrix * vec4 (VertexPosition, 1.0));\n"
"	LightDir = lightPosition - Position;\n"
"	#ifdef WITH_EYEPOSITION\n"
"		EyeVector = eyePosition-Position;\n"
"	#else\n"
"		EyeVector = -Position;\n"
"	#endif\n"
"	#ifdef WITH_COLOR\n"
"		Color = VertexColor;\n"
"	#endif\n"
"	gl_Position = ModelViewProjectionMatrix * (TransformationMatrix * vec4 (VertexPosition, 1.0));\n"
"}\n";

